version: "3.8"

services:
  giraffe-event-system:
    build:
      context: .
      dockerfile: Dockerfile
    image: udenis123/giraffe-event-system:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis # override .env REDIS_HOST to use the redis service
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    command:
      ["redis-server", "--requirepass", "vvsMgfM0FnCjk4g018qPHnP9zrOruewv"]
    ports:
      - "6379:6379"
