export enum EventType {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
  CORPORATE = 'CORPORATE',
  VIRTUAL = 'VIRTUAL',
  HYBRID = 'HYBRID',
  CONFERENCE = 'CONFERENCE',
  SEMINAR = 'SEMINAR',
  WORKSHOP = 'WORKSHOP',
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
}