export enum EventStatus {
  DRAFTED = "DRAFTED",
  REQUESTED = "REQUESTED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
  APPROVED = "APPROVED",
  POSTPONED = "POSTPONED",
  QUERIED = "QUERIED",
  REJECTED = "REJECTED",
}
