export enum EventType {
  CORPORATE = 'CORPORATE',
  VIRTUAL = 'VIRTUAL',
  HYBRID = 'HYBRID',
  CONFERENCE = 'CONFERENCE',
  SEMINAR = 'SEMINAR',
  WORKSHOP = 'WORKSHOP',
  EXHIBITION = 'EXHIBITION',
  CONCERT = 'CONCERT',
  FESTIVAL = 'FESTIVAL',
  PARTY = 'PARTY',
  WEDDING = 'WEDDING',
  BIRTHDAY = 'BIRTHDAY',
  ANNIVERSARY = 'ANNIVERSARY',
  MEETING = 'MEETING',
  TRAINING = 'TRAINING',
  TEAM_BUILDING = 'TEAM_BUILDING',
  OTHER = 'OTHER'
}