export enum VenueStatus {
  PENDING = 'PENDING',
  PUBLISHED = 'PUBLISHED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  APPROVED = 'APPROVED',
  DRAFTED = 'DRAFTED',
  REJECTED = 'REJECTED',
}